---
sudo: false
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--color --format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.10.0"
  - rvm: 2.4.2
    env: PUPPET_GEM_VERSION="~> 5.0.0"
notifications:
  email: false
